# Generated by Django 4.2.4 on 2023-08-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useraddress_address_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Admin'), ('commerciant', 'Commerciant'), ('client', 'Client')], default='client', max_length=11, verbose_name='user type'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=12, verbose_name='language'),
        ),
    ]
