# Generated by Django 4.2.4 on 2023-08-15 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_user_type_alter_userprofile_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.IntegerField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium')], default='free', verbose_name='membership type')),
                ('membership_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='membership start')),
                ('membership_end', models.DateTimeField(default=django.utils.timezone.now, verbose_name='membership end')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'membership',
                'verbose_name_plural': 'memberships',
                'ordering': ('-created_at',),
            },
        ),
    ]
