# Generated by Django 4.2.4 on 2023-08-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usermembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='membership_type',
            field=models.IntegerField(choices=[(1, 'Free'), (2, 'Basic'), (3, 'Premium')], default=1, verbose_name='membership type'),
        ),
    ]
