# Generated by Django 4.2.4 on 2023-08-21 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofile_verification_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255, verbose_name='ip')),
                ('device', models.CharField(max_length=255, verbose_name='device')),
                ('browser', models.CharField(max_length=255, verbose_name='browser')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'login',
                'verbose_name_plural': 'logins',
                'ordering': ('-created_at',),
            },
        ),
    ]
