# Generated by Django 4.2.4 on 2023-08-21 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userlogin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='device',
            new_name='device_info',
        ),
        migrations.RemoveField(
            model_name='userlogin',
            name='browser',
        ),
    ]
