# Generated by Django 4.2.4 on 2023-08-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_device_userlogin_device_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
