# Generated by Django 4.2.4 on 2023-09-08 16:12

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_translationvalue_delete_translationtext'),
        ('users', '0012_userlogin_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_to, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_profiles', to='translations.language'),
        ),
    ]
