# Generated by Django 4.2.4 on 2023-08-12 15:23

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=gallery.models.upload_to),
        ),
    ]
