# Generated by Django 4.2.4 on 2023-08-12 15:47

import django.core.validators
from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallery_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='alt',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to=gallery.models.upload_to, validators=[gallery.models.file_size, django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])]),
        ),
    ]
