# Generated by Django 4.2.4 on 2023-08-16 11:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_gallery_alt_alter_gallery_image'),
        ('products', '0002_remove_product_category_remove_product_subcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the area to engrave, e.g. "Front" or "Back"', max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('height', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='height')),
                ('width', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='width')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'engraving area',
                'verbose_name_plural': 'engraving areas',
                'ordering': ('updated_at', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the technique to engrave, e.g. "Laser" or "Embroidery"', max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('areas', models.ManyToManyField(related_name='techniques', to='products.area', verbose_name='areas')),
            ],
            options={
                'verbose_name': 'technique',
                'verbose_name_plural': 'techniques',
                'ordering': ('updated_at', 'name'),
            },
        ),
        migrations.CreateModel(
            name='AreaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.area')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_images', to='gallery.gallery')),
            ],
            options={
                'verbose_name': 'area image',
                'verbose_name_plural': 'area images',
                'ordering': ('-area',),
            },
        ),
        migrations.CreateModel(
            name='ProductEngraving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engravings', to='products.area')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engravings', to='products.product')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engravings', to='products.technique')),
            ],
            options={
                'verbose_name': 'product engraving',
                'verbose_name_plural': 'product engravings',
                'ordering': ('updated_at', 'product'),
                'indexes': [models.Index(fields=['product', 'area', 'technique'], name='products_pr_product_7cabc7_idx')],
            },
        ),
    ]
