# Generated by Django 4.2.4 on 2023-08-17 15:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
        ('products', '0003_area_technique_areaimage_productengraving'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ('updated_at',), 'verbose_name': 'engraving area', 'verbose_name_plural': 'engraving areas'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('updated_at',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ('updated_at',), 'verbose_name': 'color', 'verbose_name_plural': 'colors'},
        ),
        migrations.AlterModelOptions(
            name='composition',
            options={'ordering': ('updated_at',), 'verbose_name': 'composition', 'verbose_name_plural': 'compositions'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('updated_at',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='productseo',
            options={'verbose_name': 'product seo', 'verbose_name_plural': 'product seos'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ('updated_at',), 'verbose_name': 'product variant', 'verbose_name_plural': 'product variants'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ('updated_at',), 'verbose_name': 'size', 'verbose_name_plural': 'sizes'},
        ),
        migrations.AlterModelOptions(
            name='technique',
            options={'ordering': ('updated_at',), 'verbose_name': 'technique', 'verbose_name_plural': 'techniques'},
        ),
        migrations.RemoveField(
            model_name='area',
            name='description',
        ),
        migrations.RemoveField(
            model_name='area',
            name='name',
        ),
        migrations.RemoveField(
            model_name='area',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='color',
            name='name',
        ),
        migrations.RemoveField(
            model_name='color',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='composition',
            name='description',
        ),
        migrations.RemoveField(
            model_name='composition',
            name='name',
        ),
        migrations.RemoveField(
            model_name='composition',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='data_sheet',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='size',
            name='name',
        ),
        migrations.RemoveField(
            model_name='size',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='technique',
            name='description',
        ),
        migrations.RemoveField(
            model_name='technique',
            name='name',
        ),
        migrations.RemoveField(
            model_name='technique',
            name='slug',
        ),
        migrations.AddField(
            model_name='productseo',
            name='language',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='product_seos', to='translations.language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productseo',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.product'),
        ),
        migrations.CreateModel(
            name='TechniqueTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the technique to engrave, e.g. "Laser" or "Embroidery"', max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techniques', to='translations.language')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.technique')),
            ],
            options={
                'verbose_name': 'technique translation',
                'verbose_name_plural': 'technique translations',
                'ordering': ('-technique', 'language'),
                'indexes': [models.Index(fields=['technique', 'language'], name='products_te_techniq_b36a5b_idx')],
            },
        ),
        migrations.CreateModel(
            name='SizeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='translations.language')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.size')),
            ],
            options={
                'verbose_name': 'size translation',
                'verbose_name_plural': 'size translations',
                'ordering': ('-size', 'language'),
                'indexes': [models.Index(fields=['size', 'language'], name='products_si_size_id_14db5c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductVariantTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='translations.language')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'product variant translation',
                'verbose_name_plural': 'product variant translations',
                'ordering': ('-variant', 'language'),
                'indexes': [models.Index(fields=['variant', 'language'], name='products_pr_variant_a24b0d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Featured'), (3, 'Bestseller'), (4, 'Sale'), (5, 'New Arrivals')], default=1, verbose_name='status')),
                ('brand', models.CharField(default='Standard Wear', max_length=100, verbose_name='provider')),
                ('data_sheet', models.FileField(blank=True, null=True, upload_to=products.models.get_upload_data_sheet_path, verbose_name='data sheet')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='translations.language')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.product')),
            ],
            options={
                'verbose_name': 'product translation',
                'verbose_name_plural': 'product translations',
                'ordering': ('-product', 'language'),
                'indexes': [models.Index(fields=['product', 'language'], name='products_pr_product_2d141b_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompositionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.composition')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='translations.language')),
            ],
            options={
                'verbose_name': 'composition translation',
                'verbose_name_plural': 'composition translations',
                'ordering': ('-composition', 'language'),
                'indexes': [models.Index(fields=['composition', 'language'], name='products_co_composi_3b4722_idx')],
            },
        ),
        migrations.CreateModel(
            name='ColorTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.color')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='translations.language')),
            ],
            options={
                'verbose_name': 'color translation',
                'verbose_name_plural': 'color translations',
                'ordering': ('-color', 'language'),
                'indexes': [models.Index(fields=['color', 'language'], name='products_co_color_i_574011_idx')],
            },
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.category')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='translations.language')),
            ],
            options={
                'verbose_name': 'category translation',
                'verbose_name_plural': 'category translations',
                'ordering': ('-category', 'language'),
                'indexes': [models.Index(fields=['category', 'language'], name='products_ca_categor_5a029a_idx')],
            },
        ),
        migrations.CreateModel(
            name='AreaTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the area to engrave, e.g. "Front" or "Back"', max_length=150, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.area')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='translations.language')),
            ],
            options={
                'verbose_name': 'area translation',
                'verbose_name_plural': 'area translations',
                'ordering': ('-area', 'language'),
                'indexes': [models.Index(fields=['area', 'language'], name='products_ar_area_id_b7c76b_idx')],
            },
        ),
    ]
