# Generated by Django 4.2.4 on 2023-08-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_area_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areatranslation',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='colortranslation',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='compositiontranslation',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='productvarianttranslation',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='sizetranslation',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='techniquetranslation',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, unique=True, verbose_name='slug'),
        ),
    ]
